### ISSUE TITLE
Compile problems with the example project with VS 2017

### ISSUE THREAD

**Issue by f-rank** [datee/HaxeVLC#1]
Hi, getting this on compile

Error: VlcBitmap.cpp
./src/vlc/VlcBitmap.cpp(681): error C2573: 'vlc::VlcBitmap_obj': cannot delete pointers to objects of this type; the class has no non-placement overload for 'operator delete'.
        Use::delete, or add 'operator delete(void*)' to the class
include\vlc/VlcBitmap.h(31): note: see declaration of 'vlc::VlcBitmap_obj'

I remember trying your most excellent project with VS 2015 and not having any problems with it so it could be related to having installed VS 2017 last week to compile Armory 3D Blender projects.

**Comment by f-rank** [comment]
Found vcvarsall.bat for each install and all is well now.
Going to chalk it up to the MS being MS.

**Comment by datee** [comment]
Hm yes I'm not sure what the current status is with Haxe and Visual Studio 2017.. there could be some issues...
Will look at this at some point! Thanks anyway!

**Comment by bluelemonade** [comment]
hello, 

after searching for a cpp windows video player  I was very happy to find this repo, but I have althouhg this compiler error? how can I fix it?
