### ISSUE TITLE
.stop .resume .dispose .duration

### ISSUE THREAD

**Issue by f-rank** [datee/HaxeVLC#2]
Compiling the example project.
If I do .stop and then .play the audio continues from the point it stopped but the video stays put.
If I do .stop and then .resume and afterwards do .play it plays from the start. The .resume just makes it advance a couple of frames but it halts.
If I trace .duration it doesn't display an accurate number of frames.
.getFPS is working flawless.
.dispose doesn't look like it is working.

**Comment by datee** [comment]
Ok thanks for reporting it!
I have tested this but will see if I can reproduce the issues!

**Comment by tsmithf** [comment]
Looking into the issue with disposing VLC, I think it relates to ensuring playback has stopped before trying to dispose.

I have amended the VlxBitmap.hx file to make the dispose() function action a stop and then check if libvlc has stopped playing before trying to dispose, also then taken out the dispose() reference in the stop() function, trying it in our project and it seems to work.

These are are the changes to the two function...

	public function stop()
	{
		#if (cpp&&!mobile)
		isPlaying = false;
		libvlc.stop();
		//if (disposeOnStop)
			//dispose();
			
		if (onStop != null)
			onStop();
		#end
	}

	public function dispose()
	{
		#if (cpp && !mobile)
			libvlc.stop();
		#end
		
		stage.removeEventListener(Event.ENTER_FRAME, vLoop);
		
		if (texture != null)
		{
			texture.dispose();
			texture = null;
		}
		onVideoReady = null;
		onComplete = null;
		onPause = null;
		onPlay = null;
		onResume = null;
		onSeek = null;
		onStop = null;
		onBuffer = null;
		onProgress = null;
		onError = null;
		bufferMem = null;
		isDisposed = true;
		
		#if (cpp && !mobile)
			while (!isPlaying && !isDisposed){
				libvlc.dispose();
				libvlc = null;
			}
		#end
	}

**Comment by f-rank** [comment]
Thanks @tsmithf  will try your recommended changes.
